//auto-generated from data copy and pasted from: https://wiki.mobileread.com/wiki/MOBI#Format
exports.MobiTypeMap = {
  1: 'DRM_SERVER_ID',
  2: 'DRM_COMMERCE_ID',
  3: 'DRM_EBOOKBASE_BOOK_ID',
  100: 'AUTHOR',
  101: 'PUBLISHER',
  102: 'IMPRINT',
  103: 'DESCRIPTION',
  104: 'ISBN',
  105: 'SUBJECT',
  106: 'PUBLISHING_DATE',
  107: 'REVIEW',
  108: 'CONTRIBUTOR',
  109: 'RIGHTS',
  110: 'SUBJECT_CODE',
  111: 'TYPE',
  112: 'SOURCE',
  113: 'ASIN',
  114: 'VERSION_NUMBER',
  115: 'IS_SAMPLE',
  116: 'START_READING',
  117: 'ADULT_CONTENT',
  118: 'RETAIL_PRICE_TEXT',
  119: 'RETAIL_PRICE_CURRENCY_CURRENCY',
  121: 'KF8',
  125: 'COUNT_OF_RESOURCES',
  129: 'KF8',
  131: 'UNKNOWN',
  200: 'DICTIONARY_SHORT_NAME',
  201: 'COVER_OFFSET',
  202: 'THUMB_OFFSET',
  203: 'HAS_FAKE_COVER',
  204: 'CREATOR_SOFTWARE',
  205: 'CREATOR_MAJOR_VERSION',
  206: 'CREATOR_MINOR_VERSION',
  207: 'CREATOR_BUILD_NUMBER',
  208: 'WATERMARK',
  209: 'TAMPER_PROOF_KEYS',
  300: 'FONTSIGNATURE',
  401: 'CLIPPINGLIMIT',
  402: 'PUBLISHERLIMIT',
  403: 'UNKNOWN',
  404: 'TTSFLAG',
  405: 'UNKNOWN',
  406: 'RENT_BORROW_EXPIRATION_DATE',
  407: 'UNKNOWN',
  450: 'UNKNOWN',
  451: 'UNKNOWN',
  452: 'UNKNOWN',
  453: 'UNKNOWN',
  501: 'CDE_TYPE',
  502: 'LAST_UPDATE_TIME',
  503: 'UPDATED_TITLE',
  504: 'ASIN',
  524: 'LANGUAGE',
  525: 'WRITING_MODE',
  535: 'CREATOR_BUILD_NUMBER',
  536: 'UNKNOWN',
  542: 'UNKNOWN',
  547: 'IN_MEMORY',
}

exports.MobiTypes = {
  DRM_SERVER_ID: 1,
  DRM_COMMERCE_ID: 2,
  DRM_EBOOKBASE_BOOK_ID: 3,
  AUTHOR: 100,
  PUBLISHER: 101,
  IMPRINT: 102,
  DESCRIPTION: 103,
  ISBN: 104,
  SUBJECT: 105,
  PUBLISHING_DATE: 106,
  REVIEW: 107,
  CONTRIBUTOR: 108,
  RIGHTS: 109,
  SUBJECT_CODE: 110,
  TYPE: 111,
  SOURCE: 112,
  ASIN: 113,
  VERSION_NUMBER: 114,
  IS_SAMPLE: 115,
  START_READING: 116,
  ADULT_CONTENT: 117,
  RETAIL_PRICE_TEXT: 118,
  RETAIL_PRICE_CURRENCY_CURRENCY: 119,
  KF8: 121,
  COUNT_OF_RESOURCES: 125,
  KF8: 129,
  DICTIONARY_SHORT_NAME: 200,
  COVER_OFFSET: 201,
  THUMB_OFFSET: 202,
  HAS_FAKE_COVER: 203,
  CREATOR_SOFTWARE: 204,
  CREATOR_MAJOR_VERSION: 205,
  CREATOR_MINOR_VERSION: 206,
  CREATOR_BUILD_NUMBER: 207,
  WATERMARK: 208,
  TAMPER_PROOF_KEYS: 209,
  FONTSIGNATURE: 300,
  CLIPPINGLIMIT: 401,
  PUBLISHERLIMIT: 402,
  TTSFLAG: 404,
  RENT_BORROW_EXPIRATION_DATE: 406,
  CDE_TYPE: 501,
  LAST_UPDATE_TIME: 502,
  UPDATED_TITLE: 503,
  ASIN: 504,
  LANGUAGE: 524,
  WRITING_MODE: 525,
  CREATOR_BUILD_NUMBER: 535,
  IN_MEMORY: 547,
}

exports.MobiTypeDescriptions = {
  DRM_SERVER_ID: `drm_server_id`,
  DRM_COMMERCE_ID: `drm_commerce_id`,
  DRM_EBOOKBASE_BOOK_ID: `drm_ebookbase_book_id`,
  AUTHOR: `author		<dc:Creator>`,
  PUBLISHER: `publisher		<dc:Publisher>`,
  IMPRINT: `imprint		<Imprint>`,
  DESCRIPTION: `description		<dc:Description>`,
  ISBN: `isbn		<dc:Identifier scheme="ISBN">`,
  SUBJECT: `subject	Could appear multiple times	<dc:Subject>`,
  PUBLISHING_DATE: `publishingDate		<dc:Date>`,
  REVIEW: `review		<Review>`,
  CONTRIBUTOR: `contributor		<dc:Contributor>`,
  RIGHTS: `rights		<dc:Rights>`,
  SUBJECT_CODE: `subjectCode		<dc:Subject BASICCode="subjectcode">`,
  TYPE: `type		<dc:Type>`,
  SOURCE: `source		<dc:Source>`,
  ASIN: `asin	Kindle Paperwhite labels books with "Personal" if they don't have this record.`,
  VERSION_NUMBER: `versionNumber`,
  IS_SAMPLE: `isSample	0x0001: "if the book content is only a sample of the full book`,
  START_READING: `startReading	Position (4-byte offset) in file at which to open when first opened`,
  ADULT_CONTENT: `adultContent	Mobipocket Creator adds this if Adult only is checked on its GUI; contents: "yes"	<Adult>`,
  RETAIL_PRICE_TEXT: `retailPriceText	As text, e.g. "4.99"	<SRP>`,
  RETAIL_PRICE_CURRENCY_CURRENCY: `retailPriceCurrency currency	As text, e.g. "USD"	<SRP Currency="currency">`,
  KF8: `KF8: "BOUNDARY Offset`,
  COUNT_OF_RESOURCES: `countOfResources`,
  KF8: `KF8: "cover URI`,
  DICTIONARY_SHORT_NAME: `Dictionary short name	As text	<DictionaryVeryShortName>`,
  COVER_OFFSET: `coverOffset	Add to first image field in Mobi Header to find PDB record containing the cover image	<EmbeddedCover>`,
  THUMB_OFFSET: `thumbOffset	Add to first image field in Mobi Header to find PDB record containing the thumbnail cover image`,
  HAS_FAKE_COVER: `hasFakeCover`,
  CREATOR_SOFTWARE: `Creator Software	Known Values: 1=mobigen, 2=Mobipocket Creator, 200=kindlegen (Windows), 201=kindlegen (Linux), 202=kindlegen (Mac).`,
  CREATOR_MAJOR_VERSION: `Creator Major Version`,
  CREATOR_MINOR_VERSION: `Creator Minor Version`,
  CREATOR_BUILD_NUMBER: `Creator Build Number`,
  WATERMARK: `watermark`,
  TAMPER_PROOF_KEYS: `tamper proof keys	Used by the Kindle (and Android app) for generating book-specific PIDs.`,
  FONTSIGNATURE: `fontsignature`,
  CLIPPINGLIMIT: `clippinglimit	Integer percentage of the text allowed to be clipped. Usually 10.`,
  PUBLISHERLIMIT: `publisherlimit`,
  TTSFLAG: `ttsflag	1: - Text to Speech disabled; 0: - Text to Speech enabled`,
  RENT_BORROW_EXPIRATION_DATE: `Rent/Borrow Expiration Date	If this field is removed from a rental, the book says it expired in 1969:`,
  CDE_TYPE: `cde_type	PDOC - Personal Doc; EBOK - ebook; EBSP - ebook sample;`,
  LAST_UPDATE_TIME: `lastUpdateTime`,
  UPDATED_TITLE: `updatedTitle`,
  ASIN: `asin	I found a copy of ASIN in this record.`,
  LANGUAGE: `language		<dc:language>`,
  WRITING_MODE: `writingMode	I found horizontal-lr in this record.`,
  CREATOR_BUILD_NUMBER: `Creator Build Number	I found 1019-d6e4792: "in this record, which is a build number of Kindlegen 2.7:`,
  IN_MEMORY: `InMemory	String 'I\x00n\x00M\x00e\x00m\x00o\x00r\x00y\x00' found in this record, for KindleGen V2.9: 'build 1029-0897292:`,
}
